# Generated by Django 4.0 on 2022-01-02 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Suppliers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(max_length=50, verbose_name='supplier')),
                ('supplier_name', models.TextField(verbose_name='Description')),
            ],
        ),
    ]
