# Generated by Django 4.0 on 2022-01-02 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Destinations',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('destination', models.CharField(max_length=150, verbose_name='destination')),
                ('destination_name', models.TextField(verbose_name='DestinationName')),
            ],
        ),
    ]
