# Generated by Django 4.0 on 2022-01-02 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_destinations'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='destinations',
            options={'verbose_name': 'Destination', 'verbose_name_plural': 'Destinations'},
        ),
        migrations.AlterModelOptions(
            name='suppliers',
            options={'verbose_name': 'Supplier', 'verbose_name_plural': 'Suppliers'},
        ),
    ]
